
development:
  sessions:
    default:
      database: bodyclock
      username: bodyclock
      password: ra5sieY6
      hosts:
        - dharma.mongohq.com:10088

production:
  sessions:
      default:
        database: bodyclock
        username: bodyclock
        password: ra5sieY6
        hosts:
          - dharma.mongohq.com:10088
