
# -------------------------------------------------------------------------------
development:

    google_oauth2:
        name: Google
        app_id: 371260527969-5aijlaarh34bqbvqgotlrih2rumbp1b3.apps.googleusercontent.com
        secret: rC_vWjOZGyr4psLsbQZg961-
        options:
            :scope: userinfo.email,userinfo.profile,plus.me,http://gdata.youtube.com
            :approval_prompt: auto

# -------------------------------------------------------------------------------
production:

    google_oauth2:
        name: Google
        app_id: 371260527969-pvoqc0dng1ectb8n8u5fr3eskll3ofnd.apps.googleusercontent.com
        secret: TNDCYHw7yuVjvRe5kjywP5y1
        options:
            :scope: userinfo.email,userinfo.profile,plus.me,http://gdata.youtube.com
            :approval_prompt: auto

    yandex:
        name: Яндекс
        app_id: bf570eddf8c441ecad67cb91c79acb58
        secret: e9883f9ec09648469d0911aefc5dcfe4

    facebook:
        name: Facebook
        app_id: 358854700893028
        secret: 4b4b0fcbb0eb5d1a358a524204b947f7
        options:
            :scope: email,user_birthday,read_stream

    vkontakte:
        name: Вконтакте
        app_id: 3628707
        secret: PqmjnTMxi5STNwOu1rKQ
        options:
            :scope: notify,friends,photos,notes,docs,pages,wall,offline